### PR TITLE
Replace PointerMap with polyfill for regular Map

### PR DESCRIPTION
**Pull request by stuartpb**
Ideally, this polyfill would be left out of this project altogether (to be handled by a dedicated polyfill like CoreJS), but that can be done later.

### CODE REVIEW

**Comment by stuartpb** [comment]
Just signed the CLA, not sure why the status hasn't updated.

**Comment by scottgonzalez** [comment]
I'm not sure what this actually gets us. We're still not using the standard `Map` API even with this update.

**Comment by scottgonzalez** [comment]
In fact, won't this just throw errors in any browser that has `Map`?

**Comment by stuartpb** [comment]
This isn't using the standard Map API? What's different?

**Comment by scottgonzalez** [comment]
`Map#size` is not a function.

**Comment by stuartpb** [comment]
Right - so the polyfill should implement a getter for `size` instead of a function.

**Comment by stuartpb** [comment]
`size` uses a getter now.

**Comment by stuartpb** [comment]
Fixed tests (I think, I'm not familiar with intern).

**Comment by stuartpb** [comment]
Something appears to be going wrong now with the internal Map polyfill somehow getting set to window.Map.

**Comment by stuartpb** [comment]
I'm going to go ahead and remove [the part of the `set` test that tests internal implementation details of the polyfill](https://github.com/stuartpb/PEP/blob/21d37bee359045434231114ab5ecefde9ff0ee49/tests/unit/map.js#L29-32).

**Comment by stuartpb** [comment]
Okay, the only errors in the build now are the ones that are present in the current `master`.

**Comment by stuartpb** [comment]
So, since this is only needed to map pointers with (low) integer indices, why not just use a sparse Array to polyfill the Map?

**Comment by scottgonzalez** [comment]
We went with the sparse array implementation from gh-190.

**Pull request closed without merging**
