### PR TITLE
Add support for 3D Touch, Force Touch, and Apple Pencil tilt

### LINKED ISSUE #342: Support iOS stylus
iOS added stylus support, exposing three new properties: `touchType`, `altitudeAngle`, and `azimuthAngle`. See https://github.com/w3c/touch-events/pull/81

### PR DESCRIPTION
**Pull request by marcello3d**
## What

- add continuous pressure info when using Force Trackpads (in Safari)
- add continuous pressure info when using 3D Touch on Mobile Safari
- add tiltX/tiltY info when using Apple Pencil (on iPad) (fixes #342)
- set pointerType correctly when using Apple Pencil
- update paint sample app to render pressure
- update tracker sample app to render pressure and tilt
- fix handling of events when force is 0 (previously setting pressure to 0.5)

## Notes
- I'm new to Pointer Events, so there might be misunderstandings
- When I ran `npm test` everything failed with `unknown error: call function result missing 'value'`

### CODE REVIEW

**Comment by cjbarth** [comment]
This seems super useful. Is there anything needed to keep this moving forward?

**Comment by patrickhlauke** [comment]
Until somebody can spend some time to make this whole repo work again (Travis CI not failing, local build steps not to error out, etc), sadly there's not much that can be done I think

**Comment by cjbarth** [comment]
@patrickhlauke Does that mean that PEP is now abandoned?

**Comment by patrickhlauke** [comment]
nobody associated with the jQuery foundation seems to be willing to maintain it at present. it's open for anybody to contribute to and get it going again, but I personally lack the technical knowledge to sort out the CI/build stuff. :(

**Comment by marcello3d** [comment]
I could look at it although I’m much more familiar with circleci.

**Pull request merged**
