### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by ahocevar**
Since neither master nor any of the current pull requests pass the CI tests, I'm creating this pull request attempting to fix it.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
I have zero idea on how Travis does/doesn't work, so will have to take your word for it once you deem it ready...

**Comment by ahocevar** [comment]
I got the config working to a point now where the test suite runs in BrowserStack. But there are several test errors and many timeouts.

For fixing this, I think it makes sense focus on Safari as test browser, since it is the only recent browser without pointer events support in commonly used versions (v12). Safari added native pointer events support in v13.

**Comment by ahocevar** [comment]
Now that Travis CI is no longer used, I am closing this pull request.

On a related note: what about publishing a new version with the latest fixes on npm?

**Comment by patrickhlauke** [comment]
> On a related note: what about publishing a new version with the latest fixes on npm?

I have zero knowledge of how to go about doing that (and have been desperate for somebody more in the know to help out somehow in just tidying this up so it can be properly archived and laid to rest). Any pointers/ideas on the process?

**Comment by ahocevar** [comment]
Since you are a maintainer of https://www.npmjs.com/package/pepjs, the process is fairly simple (assuming the repo's origin on your machine is `jquery`):
```
git checkout -b jquery/master master
npx tin --bump patch # or minor or major instad of patch
npm publish
git add package.json
git commit -m "Bump version"
git push
```
I'd also recommend to create a tag.

If you don't feel comfortable doing that, I'd be happy to take on the task. You'd have to make me a maintainer of https://www.npmjs.com/package/pepjs.

**Comment by patrickhlauke** [comment]
@ahocevar sorry, coming in late, but... i tried the above, and it errors on the publish step

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/pepjs - Not found
npm ERR! 404 
npm ERR! 404  'pepjs@0.5.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

just want to get this last version published before archiving this repo...sigh

i sent you an invite as maintainer, if your kind offer still stands

**Comment by ahocevar** [comment]
@patrickhlauke Looks like you did not update the version in `package.json`. This is what `npx tin --bump patch` is supposed to do.

If you cannot make it work, I'd still be happy to help. Unfortunately I did not receive an invite for https://npmjs.com/package/pepjs. Can you try again please? My npm username is ahocevar.

**Comment by patrickhlauke** [comment]
> Looks like you did not update the version in `package.json`.

i thought i had https://github.com/jquery/PEP/commit/60644adbcf15d6dac6771f8f76620cf28d7411b5 (noting that i bumped it to 0.5.3 not 0.5.2, because for some reason in https://www.npmjs.com/package/pepjs it was already showing as 0.5.2 being the latest ... some mismatch at some point with whoever published it last?

> I did not receive an invite

odd, but i just resent and it looks like it added you correctly now :)

**Comment by ahocevar** [comment]
@patrickhlauke Very odd. I still get
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/pepjs - You do not have permission to publish "pepjs". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```
Looking at my packages, I do see `pepjs`, so I think you added me properly.

**Comment by ahocevar** [comment]
The only explanation I have is that higher version was unpublished some time. In this case it is impossible to publish a lower version.

**Comment by ahocevar** [comment]
@patrickhlauke I was able to publish v0.5.3 successfully now.

**Comment by patrickhlauke** [comment]
ah, perfect, thank you. i'll start the process of properly (hopefully) winding this repo down/mothballing things

**Pull request closed without merging**
