### PR TITLE
fix: replace const with var

### PR DESCRIPTION
**Pull request by lvdezhong**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
just checking....does this solve a particular problem? (admittedly i've not looked at this repo for ages, since it's fallen into disrepair ... but happy to merge small PRs that can at least fix some of the rougher edges)

**Comment by rj33** [comment]
> just checking....does this solve a particular problem? (admittedly i've not looked at this repo for ages, since it's fallen into disrepair ... but happy to merge small PRs that can at least fix some of the rougher edges)

Will avoid breaking any browsers old enough not to support the ES6 'const'. Given the library claims support for IE 10, which I believe doesn't support 'const' , it is probably worth merging or updating the README to say IE 11+.

**Comment by bertho-zero** [comment]
You can now use [@openagenda/pepjs](https://www.npmjs.com/package/@openagenda/pepjs).

**Comment by bertho-zero** [comment]
@patrickhlauke Please publish this or my PR.

**Comment by patrickhlauke** [comment]
CI fails, and i have no idea about publishing (presumably to npm). i'm afraid this has been an ongoing problem with this repo, as it has been abandoned and it's unclear if anybody's willing/able to take it over (at the jquery foundation or otherwise) ...

**Pull request closed without merging**
