### PR TITLE
Build: Add grunt-selenium-standalone

### PR DESCRIPTION
**Pull request by arschmitz**
Allows installation and starting of selenium standalone and chrome driver
from grunt

Fixes gh-244

### CODE REVIEW

**Comment by jzaefferer** [comment]
What would it take to integrate this into Intern? See https://github.com/theintern/digdug/issues/19

**Comment by arschmitz** [comment]
A lot more then a grunt config we would have to write the whole tunnel we have been through this with Colin we would love to do it but its a matter of time. 

We discussed this at the last meeting and decided until that is done this is a good solution

**Comment by jzaefferer** [comment]
Just checked out this branch, ran `npm install` then `grunt test`, after a while I got this error:
```sh
$ grunt test
Running "build" task
Building PEP...OK

Running "selenium_standalone:pointerevents:install" (selenium_standalone) task

Running "selenium_standalone:pointerevents:start" (selenium_standalone) task
>> Error: Missing /Users/jzaefferer/dev/jquery/pep/node_modules/selenium-standalone/.selenium/selenium-server/2.48.2-server.jar
Warning: Task "selenium_standalone:pointerevents:start" failed. Use --force to continue.

Aborted due to warnings.
```
Running with `-v` adds useless `File: [no files]` lines, nothing else of value.

**Comment by bethge** [comment]
I get the same error. Oddly, the task wants to run:
`node_modules/selenium-standalone/.selenium/selenium-server/2.48.2-server.jar` although `seleniumVersion: '2.47.1'` is set in the Gruntfile and a file with the version `2.47.1` lies in that folder: 
`node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar`

**Comment by arschmitz** [comment]
@bethge that is odd ill take a look

**Comment by bethge** [comment]
Sweet, it works!

**Comment by arschmitz** [comment]
Excellent hate to have to shrink-wrap but its the only sane fix here and i limited the shrink-wrap to just the one dependency not the whole app

**Comment by scottgonzalez** [comment]
I just went to test this and got the following error:

```
✓ scottgonzalez@:pep (pr/245)$ grunt test
Running "build" task
Building PEP...OK

Running "selenium_standalone:pointerevents:install" (selenium_standalone) task

Running "selenium_standalone:pointerevents:start" (selenium_standalone) task

Running "pretest" task

Running "intern:pointerevents" (intern) task
/Users/scottgonzalez/Projects/pep/node_modules/dojo/dojo.js:757
					throw new Error('Failed to load module ' + module.mid + ' from ' + url + (parent ? ' (parent: ' + parent.mid + ')' : ''));
					^

Error: Failed to load module intern/node_modules/dojo/node from /Users/scottgonzalez/Projects/pep/node_modules/intern/node_modules/dojo/node.js (parent: intern/node_modules/dojo/node!2!*)
    at ReadFileContext.callback (/Users/scottgonzalez/Projects/pep/node_modules/dojo/dojo.js:757:12)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
Warning: /Users/scottgonzalez/Projects/pep/node_modules/dojo/dojo.js:757
					throw new Error('Failed to load module ' + module.mid + ' from ' + url + (parent ? ' (parent: ' + parent.mid + ')' : ''));
					^

Error: Failed to load module intern/node_modules/dojo/node from /Users/scottgonzalez/Projects/pep/node_modules/intern/node_modules/dojo/node.js (parent: intern/node_modules/dojo/node!2!*)
    at ReadFileContext.callback (/Users/scottgonzalez/Projects/pep/node_modules/dojo/dojo.js:757:12)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13) Use --force to continue.

Aborted due to warnings.
```

I was using node v5.3.0, so I switch to v0.12.7 to see if that made and difference, but then I got:

```
✓ scottgonzalez@:pep (pr/245)$ grunt test
Running "build" task
Building PEP...OK

Running "selenium_standalone:pointerevents:install" (selenium_standalone) task

Running "selenium_standalone:pointerevents:start" (selenium_standalone) task
>> Error: Another Selenium process is already running
Warning: Task "selenium_standalone:pointerevents:start" failed. Use --force to continue.

Aborted due to warnings.
```

Not sure if there's a Grunt hook we can use to stop the server if an error occurs.

**Comment by arschmitz** [comment]
There is and this package normally handles it but must be a case its not handling i have a hook i wrote for something else for this let me compare whats being done

**Comment by scottgonzalez** [comment]
bump

**Comment by arschmitz** [comment]
bumped the grunt-selenium-standalone which removes need for shrinkwrap

**Comment by scottgonzalez** [comment]
Looks good.

**Pull request closed without merging**
