### PR TITLE
Update node

### PR DESCRIPTION
**Pull request by supergray**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
We'll stay with 0.10 for now since it's very popular and is what's used on our production servers.

**Comment by supergray** [comment]
__It is extremely unwise to run an ancient version of your main language on a production server :-1:__ 

Only expresses an "I don't care" mentality. Is that the thing jQuery wants to advice developers? I DON'T HOPE SO.

As you see in the travis result, the task fails on 0.12! That means incompatibility for many projects! Also, do you want to prevent every contribution to this project from people running the latest version? Once again, I DON'T HOPE SO.

@scottgonzalez, why not to discuss this before closing the issue? You are being ignorant to the rest of the community, and the rest of your team, by directly closing this. It's a shame! :hankey:

Reopen! We can always __discuss(!)__ running it on multiple versions! That's possible.

**Comment by arschmitz** [comment]
@supergray You say it fails on 0.12 yet you have included no patch to fix this only bumped versions how is this helpful to anyone? How could we possibly upgrade with out first fixing any incompatibilities?

**Comment by scottgonzalez** [comment]
> It is extremely unwise to run an ancient version of your main language on a production server

0.10 is far from ancient. It's likely in most production environments.

> As you see in the travis result, the task fails on 0.12!

It fails in 0.10 as well. What's your point?

**Comment by supergray** [comment]
> versions how is this helpful to anyone?

I did work you guys shouldn't do anymore. Just to click the merge button and you shouldn't do anything more.

> You say it fails on 0.12 yet you have included no patch to fix this

My conclusion: "we don't care about our product not working on the latest and greatest software, as we didn't update our travis settings."

> What's your point?

I was doing some work that you then shouldn't do anymore. You all don't get the meaning of a pull request.

> It fails in 0.10 as well. 

That's basically terrible. So the jQuery foundation is paying a team to build a product which isn't even working as it needs to be. FIX THAT!

> 0.10 is far from ancient. It's likely in most production environments.

Not ancient? It's more than 8 releases ago. Is this a javascript powered community or do these guys not even follow the node project?

-

Normally I submit PRs when I run into failing tests, but not anymore, thanks to @scottgonzalez. Is this the way you like open source? Fine, that's not my way.

**Comment by arschmitz** [comment]
> That's basically terrible. So the jQuery foundation is paying a team to build a product which isn't even working as it needs to be. FIX THAT!

@supergray this is pre release software. It is not intended to be production ready right now. We only just began work on getting the CI working as we begin to migrate the project from its original home as part of polymer if you check the commit history there have only been a handful of commits since we took over the project. I strongly advice you to exercise patience as we get this ready for production use. 

@supergray Also please not that the jQuery Foundation is almost entirely volunteer time.

**Comment by scottgonzalez** [comment]
> Just to click the merge button and you shouldn't do anything more.

Sorry, it doesn't work that way. Pull request must provide value and contributions must be accompanied by a CLA. You seem to have completely ignored the contribution process.

> My conclusion: "we don't care about our product not working on the latest and greatest software, as we didn't update our travis settings."

PEP isn't for use in node. The build tasks work just fine in all recent versions of node, even if we're not using node 0.12.x in our test infrastructure.

> That's basically terrible. So the jQuery foundation is paying a team to build a product which isn't even working as it needs to be. FIX THAT!

I'm sorry that you're upset by the fact that we have failing tests in alpha software. The world isn't perfect. We're aware of the failures and are working to fix them. This, however, has absolutely nothing to do with what version of node you're using.

> Not ancient? It's more than 8 releases ago. Is this a javascript powered community or do these guys not even follow the node project?

0.10.37 was released a whopping 12 days ago. The most recent 0.12.x release is 0.12.0. At most, we're one version behind. I fail to see how that's ancient. I have no idea where you got the number eight from.

> Normally I submit PRs when I run into failing tests, but not anymore, thanks to @scottgonzalez.

I fail to see where you did that. Not just for this project, but for your entire history on GitHub.

If you'd like to be cooperative and work on actual failing tests we'd be happy to review additional PRs.

**Comment by supergray** [comment]
> This, however, has absolutely nothing to do with what version of node you're using.

Why wouldn't this have anything to do with node? It's the freaking programming envirment you're working in.

> I'm sorry that you're upset by the fact that we have failing tests in alpha software. The world isn't perfect. 

You can't talk about software when something doesn't work.

> If you'd like to be cooperative and work on actual failing tests we'd be happy to review additional PRs.

After you were rude to me? Yeah right. Of course.

> Pull request must provide value 

So a pull request doing something that you wouldn't have done later on does not make sense. Doing great, guys.

> I fail to see where you did that.

Is this a personal attack? Basically rude.
 
-

@dmethvin Hi mister president. I would like to talk to you about the conduct of your team members. Can we have a chat?

**Pull request closed without merging**
