### PR TITLE
update travis-ci settings

### PR DESCRIPTION
**Pull request by adrukh**
Trying my luck at tidying up the CI settings with travis

### CODE REVIEW

**Comment by adrukh** [comment]
👋 @patrickhlauke 

This is as far as I can take this for now. Can you perhaps shed some light on how to test this properly on my local env? I must be missing something as the tests are failing miserably for me:
```
JavaScriptError: [POST http://localhost:4444/wd/hub/session/04496c32-1969-4999-b2a3-292951262e85/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t\t(function poll() {\n\t\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse {\n\t\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t})();\n\t\t\t\t\t}).apply(this, arguments);","args":["return (function () {\n\t\t\t\t\treturn window.w3cTests;\n\t\t\t\t}).apply(this, arguments);",[],1000,67]}] unknown error: call function result missing 'value'
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.13.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'antons-mbp.lan', ip: '192.168.1.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_152'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1), userDataDir=/var/folders/47/nhtc99rd4ds98kqz289ktrkr0000gn/T/.org.chromium.Chromium.CeikK0}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=70.0.3538.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 813027e6a607df9b9cb426fb6426666e
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.executeAsync  <node_modules/intern/node_modules/leadfoot/Session.js:745:15>
  at <node_modules/intern/node_modules/leadfoot/helpers/pollUntil.js:90:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at new CustomCommand  <tests/support/w3cTest.js:29:11>
  at CustomCommand.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at CustomCommand.<anonymous>  <tests/support/w3cTest.js:37:6>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:132:7>
  at process._tickCallback  <internal/process/next_tick.js:181:9>
  at new CustomCommand  <tests/support/w3cTest.js:29:11>
  at CustomCommand.checkResults  <tests/support/w3cTest.js:35:10>
  at Test.main [as test]  <tests/functional/pointerevent_setpointercapture_relatedtarget-manual.js:28:6>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:132:7>

=============================== Coverage summary ===============================
Statements   : 14.9% ( 93/624 )
Branches     : 7.42% ( 23/310 )
Functions    : 7.09% ( 10/141 )
Lines        : 15% ( 93/620 )
================================================================================
>> chrome on any platform: 30/30 tests failed; fatal error occurred

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
 dist/    |     14.9 |     7.42 |     7.09 |       15 |                |
  pep.js  |     14.9 |     7.42 |     7.09 |       15 |... 6,1440,1445 |
----------|----------|----------|----------|----------|----------------|
All files |     14.9 |     7.42 |     7.09 |       15 |                |
----------|----------|----------|----------|----------|----------------|

>> TOTAL: tested 1 platforms, 30/30 tests failed

Error: One or more suite errors occurred during testing
  at <node_modules/intern/lib/executors/Executor.js:314:13>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:132:7>
  at process._tickCallback  <internal/process/next_tick.js:181:9>
Warning: Test failure; check output above for details. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

**Comment by patrickhlauke** [comment]
sadly i have no idea about any of the build scripts, travis, selenium etc. hoping perhaps somebody else who may be watching this repo may have an insight?

**Comment by mattmachell** [comment]
It might just be that the version of Chromedriver configured is too old for the version of Chrome used. i.e. Chrome 70 may be too late for the 2.25 of Chromedriver. 

Could try a bump to Chromedriver 2.44 (latest) and see if that works.

https://github.com/jquery/PEP/blob/master/Gruntfile.js#L73

http://chromedriver.chromium.org/downloads shows version hints and 2.42 was the first to mention Chrome 70.

**Comment by adrukh** [comment]
@mattmachell thanks, that gave me a push forward! Seeing real functional failures locally, will try to bridge the gap on travis to see the same.

**Comment by adrukh** [comment]
Apologies folks, I won't be able to push this forward as I thought. Hope I didn't steal the attention of more competent folks!

If anyone has an idea about this one, please proceed. I'd understand if this PR was closed 😞

**Comment by patrickhlauke** [comment]
hey no worries, and thanks for giving it a shot so far. i'll see if i can rally some more troops. leaving this open for now just in case it can be used as a starting point.

**Comment by patrickhlauke** [comment]
removed CI integration to wind this repo down soon, so closing this

**Pull request closed without merging**
