### PR TITLE
Fix CSS capitalization in README.

### PR DESCRIPTION
**Pull request by adjohnson916**

### CODE REVIEW

**Comment by adjohnson916** [comment]
@jzaefferer Thanks - my CLA sign failed, I think due to using a `@users.noreply.github.com` address, even though that's what I use for my commits...

**Comment by scottgonzalez** [comment]
That's correct. As [the status page says](http://contribute.jquery.org/CLA/status/?repo=PEP&sha=0ea2553575d40ff1ee3058f1defa91f61dfe8931), "adjohnson916@users.noreply.github.com is a private GitHub email address."

We don't accept noreply email addresses because we can never contact the author if needed.

**Comment by adjohnson916** [comment]
@scottgonzalez But I commit with that email, and it has to match commits also, right?

**Comment by scottgonzalez** [comment]
Yes, which means that you need to commit and sign with a different email address.

**Pull request closed without merging**
